# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DCEmptyViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'EmptyView', :git => 'https://github.com/XGG17/EmptyView.git'

  # Pods for DCEmptyViewDemo

  target 'DCEmptyViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DCEmptyViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
